environment: kubes-environment
apphost: kubes-host

label:
  name: helmplay

container:
  name: coreapp31-kube-helm
  pullPolicy: IfNotPresent
  image: helmplay
  tag: v1
  port: 80
replicas: 3

service:
  port: 8888
  type: ClusterIP